<a href="https://colab.research.google.com/github/visiont3lab/machine-learning-course/blob/main/python/Class_27_11_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import *
#fdfsd
def mytest():
    d = {'col1': [1, 2], 'col2': [3, 4]}
    df = ptest.DataFrame(data=d)
    return df

def mytest_2():
    d = {'col1': [1, 2], 'col2': [3, 4]}
    df = ptest.DataFrame(data=d)
    return df

In [ ]:
from mylib import *
mytest_2()

col1  col2
0     1     3
1     2     4

In [ ]:
bash

In [ ]:
!mkdir manuel

In [ ]:
!cp mylib.py manuel/

In [ ]:
!rm mylib.py

In [ ]:
#df = pandas.DataFrame({"ciao": [1,3,4], "hello" : [2,3,4]})

'''
ciao come stati
a = 4
'''

a = 4

print(b+a)
b = 6

print(b)

In [ ]:
!pip uninstall pandas 
!pip install pandas==1.1.2 
!pip search pandas 
!pip list | grep pandas
!pip freeze > requirements.txt

In [ ]:
# --> import 
# --> multiplicazione
# --> def

In [ ]:
!pip install requests 

In [ ]:
import requests
def requestHttp(url='https://www.google.it/'):
    r =requests.get(url)
    return r.text
print(requestHttp())

In [ ]:
!pip install selenium

     |████████████████████████████████| 911kB 5.6MB/s 


In [ ]:
# Funzioni
def my_sum(inp1,inp2=10,inp3=15):
    c = inp1+inp2
    print(c)

def my_sum1(inp1,inp2=10,inp3=15):
    sum = inp1+inp2
    mult = inp1*inp2
    t = sum + inp1
    return sum,mult,t

def my_sum2(inp1,inp2=10,inp3=15):
    c = inp1+inp2
    return c

#suym, myult,ty = my_sum1(8)
val = 15
print(val)
a,b,_ = (val,5,6)
print(a)



15
15


In [ ]:
# https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
!wget https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd
#%load_ext google.colab.data_table

def get_deceduti_oggi():
    df = pd.read_csv("dpc-covid19-ita-andamento-nazionale.csv")
    #num_deceduti = df.tail(1)["deceduti"].values[0]
    res = df.tail(1)[["data","deceduti","totale_casi"]].values.tolist()[0]
    data = res[0]
    deceduti = res[1]
    totale_casi = res[2]
    return data,deceduti,totale_casi

def print_dataset():
    df = pd.read_csv("dpc-covid19-ita-andamento-nazionale.csv")
    display(df)

print_dataset()
data,deceduti,totale_casi = get_deceduti_oggi()
print("Data %s ---- Numero deceduti: %s ---- Totale Casi: %s" % (data,deceduti,totale_casi)) 


# Esercizio plottare l'andamento giornaliero
# http://opendatadpc.maps.arcgis.com/apps/opsdashboard/index.html#/b0c68bce2cce478eaac82fe38d4138b1

In [ ]:
df = pd.read_csv("dpc-covid19-ita-andamento-nazionale.csv")
res = df.tail(1)[["deceduti","data"]].values.tolist()[0]
deceduti = res[0]
data = res[1]
print(deceduti,data)

53677 2020-11-27T17:00:00


In [ ]:
a = {
    "deceduti" : [150,45],
    "data" : ["2020-11-10","djkdsj"],
    "test" : ["dsds-11-10", "ñs"]
}
table = pd.DataFrame(a)
table.values

array([[150, '2020-11-10', 'dsds-11-10'],
       [45, 'djkdsj', 'ñs']], dtype=object)

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Braund, Mr. Owen Harris",
                "Allen, Mr. William Henry",
               "Bonnell, Miss. Elizabeth"],
    "Age": [22, 35, 58],
    "Sex": ["male", "male", "female"]}
    )
   
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

## Update lezione 27-11-2020

### TODO:

*  Conessione a drive da colab
* Array - Lista - Classe
* Pandas


# Titolo
## Sottottilo
fdsfds
fdsf
## Sottottilo
1. [fdsfds](http://chromedriver.chromium.org/downloads?tmpl=%2Fsystem%2Fapp%2Ftemplates%2Fprint%2F&showPrintDialog=1)
2. fdsf

### Sottottilo


kfjdlskfds

fds

# Introduzione a oggetti di python


## Liste

1. Dimensione fissa
2. Contenere diversi tipi (int,float,string,classe, lista)
3. Lista può essere ordinata
4. Una lista ha una lunghezza ma non ha una shape (dimensione)

In [43]:
import numpy as np

a = [1,2,3,4]
#a = ["jk", 2,    5.0,    [3,4,["jkj","2",45]],  np.array([3,5])]
#print(type(a))
#a[3][2][0]

# lunghezza di una lista
print("Lunghezza lista a: ", len(a))
# Per i che va 0 a 3 (3-1)
#for i in range(0,len(a)):
#  print(a[i])

# per ogni elemento/valore contenuto nella lista a
#for el in a:
#  print(el+5)

# Aggiungi a tutti gli elementi della lista a +5 e ritornami una lista nuova

# Risultato

# Array
a = list(np.array(a, dtype=np.int64) * 5)
display(a)

# --------
l = []
a = [1,2,3,4,5]
for el in a:
  l.append(el+5)

# --------
l = [el+5 for el in a]
display(l)

# ------
a = [1,0,2,3,4]
for kappa in range(0,len(a)):
#for kappa in a:
  print(kappa)
  #a[i] = a[i] + 5



Lunghezza lista a:  4


[5, 10, 15, 20]

[6, 7, 8, 9, 10]

0
1
2
3
4


In [51]:
# ----- Ordinare una lista
a = ["c","b", "m"]
a = [1,4,7,3]
a.sort() # lista ordianta
a.sort(reverse=True) # lista al contrario
a

[7, 4, 3, 1]

## Numpy Array

In [60]:
# agli array si accede solo tramite indici e la dimensione è fissa
# la decido alla creazioni
a = np.array([ [4.5,6,7,8],[4.5,6,7,8] ]) # matrice 2x4
print(a.shape)
a[0][1]

(2, 4)


6.0

In [87]:
#a = list(np.array([5,6,7]))
#5   6    7
#78 658  586
# Gli multiwise moltiplation
m = np.power(np.array([5,6,7]),3) * (np.array([5,6,7])+3)
m = list(m)
m.append(5)
m

[1000, 1944, 3430, 5]

In [95]:
a = [1,4,5]
b = [3,4,5]
# Prodotto scalare 1*3 + 4*4 + 5*5
test = 1*3 +4*4 +5*5
#print(np.dot(a,b))
np.dot(a,b)

44

In [102]:
#  3 4 5
#  5 6 7
table = np.array([ [[3,4,5], [5,6,7]], [[3,4,5], [5,6,7]] , [[3,4,5], [5,6,7]] ])
table.shape


(3, 2, 3)

In [106]:
x = np.array([5,8,9,10])
y = np.array([15,65,56,50])
z = np.array([50,854,95,100])
v = np.array([[x],[y],[z]])
v.shape

#1980x720 HD
#640x480 --> VGA --> 0-255 --> r (0-255) - g (0-255) -b (0-255)
# [ 0   25  75 
#    0   36  65
#   12 215 255    ]
#(3,640,480,3)
#(3,640,3,480)
#(3,3,640,480)
#a[0,0:640,0:480,0]


(3, 1, 4)

In [ ]:
# Sensori mandano dati cloud --- Tu ti fai un proghramm che parla con il plc (c#,c++, python)
# Mqtt / Websocket
# Archiviazione dei dati Database Realtime influxdb / 1 volte al secondo -- Mysql -- Postrgress
# Dashboard che prende i dati dal tabase
# Graphana influxdb -- facile (opensoruce) 
# #--- Elastic search -- difficile
# PowerBi facile microsoft
# timesiries anomaly detection <-- Dani

In [133]:
#a = np.ones((3,6))*5
#a = np.zeros((3,6))
a = np.array([[4,5,6]])
b = np.array([[6,8,9]])
m = np.concatenate((a,b),axis=0)  # verticale
print(m)
m.reshape(-1)
#m = np.concatenate((a,b),axis=1) # orizzontale
#print(m.shape)
#m

[[4 5 6]
 [6 8 9]]


array([4, 5, 6, 6, 8, 9])

In [130]:
a = np.array([4,5,6]) # 1x3
print(a)
a = a.reshape(3,1)
print(a)
a.shape

[4 5 6]
[[4]
 [5]
 [6]]


(3, 1)

## Esercizio (Dizionari)

In [141]:
import pandas as pd
url ="https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv"
df = pd.read_csv(url)
#df.head(2) # fammi vedere i primi
#df.tail(2) # fammi vedere gli ultimi

data stato  ...  casi_testati  note
279  2020-11-29T17:00:00   ITA  ...    12922382.0   NaN
280  2020-11-30T17:00:00   ITA  ...    12986634.0   NaN

[2 rows x 17 columns]

In [153]:
nomi_delle_colonne = list(df.keys())
df.values.shape

(281, 17)

In [162]:
df.values.shape

(281, 17)

In [195]:
a = {
    "nome" : np.array([1,3,5]),
    "Cognomi" : np.array([8,9,165])
}
mini_df = pd.DataFrame(a)
display(mini_df)
#print(mini_df.shape)
mini_df.values[0:3,1]
#print("Nomi delle colonne: ", list(a.keys()))
#m = np.array(a.values())
#m

mini_df["Cognomi"].values[1:2] # prendi da 1 a 2 dove 2 è escluso
mini_df["Cognomi"].values[1]
mini_df["Cognomi"].values[[0,2]]
mini_df["Cognomi"].values[-1]
mini_df["Cognomi"].values[-2:-1]
mini_df["Cognomi"].values[0:] # da zero all'ultimo
mini_df["Cognomi"].values[0:-2] # da primo 0 al penultimo

nome  Cognomi
0     1        8
1     3        9
2     5      165

array([8])

## Esercizio  

> Calcolare l'incremento giornaliero della terapia intensiva


In [231]:
import pandas as pd
import numpy as np
url ="https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv"
df = pd.read_csv(url)
# L'ultima riga è la data di oggi
# La penultima riga è la data di ieri
display(df.tail(2)) # 3753 - 3744 = 9
#df.values
list(df.keys())

data stato  ...  casi_testati  note
279  2020-11-29T17:00:00   ITA  ...    12922382.0   NaN
280  2020-11-30T17:00:00   ITA  ...    12986634.0   NaN

[2 rows x 17 columns]

['data',
 'stato',
 'ricoverati_con_sintomi',
 'terapia_intensiva',
 'totale_ospedalizzati',
 'isolamento_domiciliare',
 'totale_positivi',
 'variazione_totale_positivi',
 'nuovi_positivi',
 'dimessi_guariti',
 'deceduti',
 'casi_da_sospetto_diagnostico',
 'casi_da_screening',
 'totale_casi',
 'tamponi',
 'casi_testati',
 'note']

In [199]:
df['terapia_intensiva'].tail(2).values[0]-df['terapia_intensiva'].tail(2).values[1] 

9

In [210]:
import pandas as pd
def incremento(df,colonna):
  incremento = df[colonna].values[-1] - df[colonna].values[-2]
  return incremento

url ="https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv"
df = pd.read_csv(url)
result = incremento(df,["terapia_intensiva","deceduti","totale_casi"])
print(result)


-9


In [213]:
TI2 = df.tail(2)["terapia_intensiva"].values[1]-df.tail(2)["terapia_intensiva"].values[0] 
TI2

-9

In [228]:
ti=df["terapia_intensiva"]
arr = ti.values
l = arr.shape[0]
ti[l-1]-ti[l-2] 

281


-9

In [230]:
a = np.array(df.tail(2)["terapia_intensiva"])
b = a[1]-a[0]  
b

-9

In [ ]:
"totale_casi","totale_positivi","deceduti","dimessi_guariti"

In [243]:
df.values.shape
search = ["totale_casi","totale_positivi","deceduti","dimessi_guariti"]
df[search].values[-1]

array([1601554,  788471,   55576,  757507])

In [258]:
# Mi da il risultato della funziones
# NO : function / void
def nomeacaso(df, mialista=["terapia_intensiva", "deceduti", "totale_casi"]):
  listanuova = []
  for el in mialista:
    temp = df[el].values[-1]-df[el].values[-2]
    listanuova.append(temp)
  return mialista, listanuova # dammi indietro

mialista, listanuova = nomeacaso(df)
print(listanuova)

[-9, 672, 16376]


In [260]:
import pandas as pd

def incremento_versione2(df,lista_colonne):
  l=[]
  for elemento in lista_colonne:
    incremento = df[elemento].values[-1] - df[elemento].values[-2]
    l.append(incremento)
  return incremento

def get_data(df,lista_colonne):
  incremento = df[lista_colonne].values[-1]-df[lista_colonne].values[-2]
  oggi = df[lista_colonne].values[-1]
  return list(oggi), list(incremento) 


url ="https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv"
df = pd.read_csv(url)
result = incremento_versione2(df,["terapia_intensiva", "deceduti", "totale_casi"])
oggi, incremento = get_data(df,["terapia_intensiva", "deceduti", "totale_casi"])
print(oggi,incremento)

[3744, 55576, 1601554] [-9, 672, 16376]


In [267]:
# Roberta
def dftake(a, b, c):
  print(a,b,type(c))
  T = df.tail(a)[c].values[b+1]-df.tail(a)[c].values[b]
  return T

k= list(df.keys())
k
type(k[1])
for el in k:
  m = 2
  n = 0
  o = el
  TI2 = dftake(m, n, o)


2 0 <class 'str'>


TypeError: ignored

In [ ]:
def calc_incremento_giornaliero(c,df): 
  a = np.array(df.tail(2)[c]) b = a[0]-a[1]
  print( "Incremento giornaliero %s " ,b)) 
  #type(df.columns) calc_incremento_giornaliero('deceduti',df) 

In [271]:
# Stringa
a = "ciao"
print("Ciao ciao mkjdlskdlk: " + a)
print("Ciao ciao mkjdlskdlk: %s" % (a))


Ciao ciao mkjdlskdlk: ciao
Ciao ciao mkjdlskdlk: ciao
