<a href="https://colab.research.google.com/github/visiont3lab/machine-learning-course/blob/main/python/PythonColabIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduzione a Google Colab

Google colab è un software di google

## Linguaggio Bash

In [ ]:
import numpy as np

In [ ]:
!nvidia-smi 

In [ ]:
# Visualizzare le librerie python installate
!pip list | grep tor

In [ ]:
# listami i file contenuti nella cartella
!ls

sample_data


In [ ]:
# in che cartella sono
!pwd

/content


In [ ]:
# crear un file 
!touch manuel.txt

In [ ]:
!rm manuel.txt

In [ ]:
!git clone https://github.com/visiont3lab/machine-learning-course.git
# github gitlab bitbucket

In [ ]:
!git clone -h

In [ ]:
!wget https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

## Python introduzione

In [ ]:
# installare librerie
!pip uninstall names

Found existing installation: names 0.3.0
Uninstalling names-0.3.0:
  Would remove:
    /usr/local/bin/names
    /usr/local/lib/python3.7/dist-packages/names-0.3.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/names/*
Proceed (y/n)? y
  Successfully uninstalled names-0.3.0


In [ ]:
!pip list | grep names

In [ ]:
pip # packet manager

In [ ]:
import names as n
n.get_full_name()

'David Reynolds'

In [ ]:
!pip install names

In [ ]:
# Python
!bash

## Markdown





* dsds
* dsds
* dsds

1. fdf
2. 343
3. **fdsfd**

> kldskf **fsdkldk** *flsdf* fsd



```javascript
import numpy as np
```


---

## Python basics

In [ ]:
!pip install names

In [ ]:
import names
import numpy as np

In [ ]:
names.get_full_name()

'Vikki Howe'

In [ ]:
# Creami  10 nome a caso e stampali
for i in range(0,5): #1-(10-1))
  fullname = names.get_last_name()
  print(fullname)

# Creami  10 nome a caso e stampali
for i in range(0,5): #1-(10-1))
  fullname = names.get_last_name()
  print(fullname)

# Creami  10 nome a caso e stampali
for i in range(0,5): #1-(10-1))
  fullname = names.get_last_name()
  print(fullname)

# Creami  10 nome a caso e stampali
for i in range(0,5): #1-(10-1))
  fullname = names.get_last_name()
  print(fullname)

# Creami  10 nome a caso e stampali
for i in range(0,5): #1-(10-1))
  fullname = names.get_last_name()
  print(fullname)

Bulmer
Richardson
Brown
Griffy
Averitt
Cunningham
Watkins
Jaquet
Curry
Gilmour
Hall
Anderson
Martinez
Davis
Luzar
Garcia
Minor
Gonzalez
Truett
Beliveau
Freeman
Patrick
Angelilli
Rogers
Feliciano


In [ ]:
def create_random_names(numero):
  # Creami  10 nome a caso e stampali
  for i in range(0,numero): #1-(10-1))
    fullname = names.get_last_name()
    print(fullname)

create_random_names(numero=5)
create_random_names(numero=5)
create_random_names(numero=5)
create_random_names(numero=5)


In [ ]:
# tupla
a,v = [4,["ciao"]]
display(a,v)

4

['ciao']

In [ ]:
def nome_della_funzione(input1, input2):
  return "Ciao: " + str(input1), "ho fame"  # --> Tupla

display( nome_della_funzione(4,5)[1] )
b=5

'ho fame'

In [ ]:
def create_random_names(numero=5):
  # Creami 10 nome a caso e stampali
  fullnames = []
  for i in range(0,numero): #1-(10-1))
    fullname = names.get_last_name()
    fullnames.append(fullname)
  return fullnames, len(fullnames)

fullnames, lennames = create_random_names(numero=6)
display(fullnames)
display(lennames)

['Stuble', 'Dwyer', 'Brown', 'Franzen', 'Lawrence', 'Cruz']

6

In [ ]:
# le liste sono iterabili!
b = 5
a = ['manuel', 4,'sara',np.array([4,5,6]),['francesco' ,'davide']]
#display(a)
display(a)
display(b)

['manuel', 4, 'sara', array([4, 5, 6]), ['francesco', 'davide']]

5

In [ ]:
len(a)

5

In [ ]:
a = ['manuel','chiara','francesco']
a.extend(["davide","gianni"])
a.append('marco')
a

['manuel', 'chiara', 'francesco', 'davide', 'gianni', 'marco']

In [ ]:
a = ['manuel', 4,'sara',np.array([4,5,6]),['francesco' ,'davide']]

[print(el) for el in a]

for el in a:
  print(el)
  
for i in range(0,len(a)):
  print(a[i])

manuel
4
sara
[4 5 6]
['francesco', 'davide']
manuel
4
sara
[4 5 6]
['francesco', 'davide']
manuel
4
sara
[4 5 6]
['francesco', 'davide']


In [ ]:
def dskdl():
  for i in range(0,2):
    fsdfds

In [ ]:
c[1][1]
c[1,1]
c[0,-3:] # dammi tutti gli elementi della prima riga

array([4, 5, 6])

In [ ]:
c

array([[4, 5, 6],
       [4, 5, 6],
       [4, 5, 5],
       [4, 5, 6]])

In [ ]:
c.shape

(4, 3)

In [ ]:
c = np.array( [ 
           [4,5,6],
           [4,5,6],
           [4,5,5],
           [4,5,6] ]
        )
display( c.shape )

c1 = np.array( [ 
           [4,5],
           [4,5],
           [4,5],
           ]
        )
display(c1.shape)

# Operazioni
np.matmul( c, c1)

(4, 3)

(3, 2)

array([[60, 75],
       [60, 75],
       [56, 70],
       [60, 75]])

In [ ]:
a = np.array([  [3.0,4,5]  ])
a.dtype
a.shape

(1, 3)

In [ ]:
a = a.T
a.shape

(3, 1)

## Esercizio

* importare la libreia pandas. Se non è installata la installiamo
* leggere un file csv
* lavoriamo con i numpy array

In [ ]:
!wget https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

--2021-10-14 18:29:57--  https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 77118 (75K) [text/plain]
Saving to: ‘dpc-covid19-ita-andamento-nazionale.csv’

dpc-covid19-ita-and 100%[===================>]  75.31K  --.-KB/s    in 0.009s  

2021-10-14 18:29:58 (8.30 MB/s) - ‘dpc-covid19-ita-andamento-nazionale.csv’ saved [77118/77118]



In [ ]:
!ls

dpc-covid19-ita-andamento-nazionale.csv  sample_data


In [ ]:
# dizionario
a = {
    "colonna1": np.array([4,5]),
    "colonna2": np.array([1,3]), 
}
a.values()

dict_values([array([4, 5]), array([1, 3])])

In [ ]:
import pandas as pd
#df = pd.read_csv("dpc-covid19-ita-andamento-nazionale.csv")
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv")
#df.head() # primi 5 elementi di questo dataset
#n = df.keys()
#arr = df.values
# arr.shape

In [ ]:
df.values

array([['2020-02-24T18:00:00', 'ITA', 101, ..., nan, nan, nan],
       ['2020-02-25T18:00:00', 'ITA', 114, ..., nan, nan, nan],
       ['2020-02-26T18:00:00', 'ITA', 128, ..., nan, nan, nan],
       ...,
       ['2021-10-12T17:00:00', 'ITA', 2665, ..., 173740.0, 61308451.0,
        34452781.0],
       ['2021-10-13T17:00:00', 'ITA', 2552, ..., 173944.0, 61428982.0,
        34611195.0],
       ['2021-10-14T17:00:00', 'ITA', 2479, ..., 174156.0, 61540896.0,
        34823895.0]], dtype=object)

In [ ]:
def incremento(df, nome_colonna):
  diff1 = df[nome_colonna].values[-1] - df[nome_colonna].values[-2]
  diff2 = df[nome_colonna].values[-1] - df[nome_colonna].values[-4]
  last = list ( df[nome_colonna][-5:].values )
  return diff1, diff2, last 

a,b,c = incremento(df, "nuovi_positivi") 

display( a,b,c )
display( incremento(df, "deceduti") )

for el in c:
  print(el)


-104

1152

[2278, 1516, 2494, 2772, 2668]

(40, 126, [131301, 131335, 131384, 131421, 131461])

2278
1516
2494
2772
2668


In [ ]:
import numpy as np
m = ["manuel", 4 , np.array([4,6]) ]
lista= [[3.4,6,7]]
array = np.array(lista).flatten()
print(array.shape)
print(array)
lista = list(array)
lista

(3,)
[3.4 6.  7. ]


[3.4, 6.0, 7.0]

In [ ]:
m = np.array([3,4,5])
print( type(m) )
m = list(m)
print( type(m) )

k = [3,4,5]
print( type(k) )
k = np.array(k)
print( type(k) )

<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#array e liste

In [ ]:
df["ricoverati_con_sintomi"].values

In [ ]:
import numpy as np
a = np.array([43,5,6])
for el in list(a):
    print(el)

43
5
6


## Esercizio

> trovate gli incrementi giornaliero degli ultimi 5 giorni dei ricoverati con sintomo, deceduti, nuovi positivi

* Importare pandas
* avere le colonne come array
* for che vi calcola l 'incremento
* ritornate il risultato come lista / dizionario

